export const shopifySites = [
  { value: 'custom_sh092', label: 'Custom' },
  { value: 'https://www.12amrun.com', label: '12amrun' },
  { value: 'https://www.abovethecloudsstore.com', label: 'Above the Clouds' },
  { value: 'https://www.addictmiami.com', label: 'Addict Miami' },
  { value: 'https://alifenewyork.com', label: 'Alife New York' },
  { value: 'https://www.alumniofny.com', label: 'Alumini New York' },
  { value: 'https://www.a-ma-maniere.com', label: 'A Ma Maniere' },
  { value: 'https://www.amongstfew.com', label: 'Amongst Few' },
  { value: 'https://shop.antisocialsocialclub.com', label: 'Anti Social Social Club' },
  { value: 'https://astoreisgood.com', label: 'A Store is Good' },
  // {value: 'https://www.atmosny.com', label: 'Atmos New York'},
  { value: 'https://us.bape.com', label: 'Bape US' },
  { value: 'https://www.bbbranded.com', label: 'BB Branded' },
  { value: 'https://shop.bbcicecream.com', label: 'Billionare Boys Club' },
  { value: 'https://bdgastore.com', label: 'Bodega' },
  { value: 'https://biancachandon.com', label: 'Bianca Chandon' },
  { value: 'https://www.blendsus.com', label: 'Blends' },
  { value: 'https://www.capsuletoronto.com', label: 'Capsule Toronto' },
  { value: 'https://www.cityblueshop.com', label: 'City Blue' },
  // {value: 'https://cncpts.com', label: 'Concepts'},
  { value: 'https://commonwealth-ftgg.com', label: 'Commonwealth FTGG' },
  { value: 'https://www.concrete.nl', label: 'Concrete NL' },
  { value: 'https://www.courtsidesneakers.com', label: 'Courtside Sneakers' },
  { value: 'https://www.darksidesf.com', label: 'Darkside' },
  { value: 'https://www.deadstock.ca', label: 'Deadstock CA' },
  { value: 'https://eflash-jp.doverstreetmarket.com', label: 'DSM JP' },
  { value: 'https://eflash.doverstreetmarket.com', label: 'DSM' },
  { value: 'https://eflash-us.doverstreetmarket.com', label: 'DSM US' },
  { value: 'https://eflash-sg.doverstreetmarket.com', label: 'DSM SG' },
  { value: 'https://www.dtlr.com', label: 'DTLR' },
  { value: 'https://www.ericemanuel.com', label: 'Eric Emanuel' },
  { value: 'https://shop.extrabutterny.com', label: 'Extra Butter New York' },
  { value: 'https://fearofgod.com', label: 'Fear of God' },
  { value: 'https://shop.funko.com', label: 'Funko Shop' },
  { value: 'https://fuckthepopulation.com', label: 'Fuck the Population' },
  { value: 'https://www.hanon-shop.com', label: 'Hanon' },
  { value: 'https://shop.havenshop.com', label: 'Haven' },
  { value: 'https://www.hlorenzo.com', label: 'H Lorenzo' },
  { value: 'https://www.jimmyjazz.com', label: 'Jimmy Jazz' },
  { value: 'https://kawsone.com', label: 'Kaws One' },
  { value: 'https://kith.com', label: 'Kith' },
  { value: 'https://laceupnyc.com', label: 'Laceup New York' },
  { value: 'https://www.lapstoneandhammer.com', label: 'Lapstone and Hammer' },
  { value: 'https://noirfonce.eu', label: 'Noirfence EU' },
  { value: 'https://www.notre-shop.com', label: 'Notre' },
  { value: 'https://nohble.com', label: 'Nohble' },
  { value: 'https://nrml.ca', label: 'NRML CA' },
  { value: 'https://store.obeygiant.com', label: 'Obey' },
  { value: 'https://us.octobersveryown.com', label: 'Octobers Very Own' },
  { value: 'https://www.offthehook.ca', label: 'Off the Hook CA' },
  { value: 'https://packershoes.com', label: 'Packer Shoes' },
  { value: 'https://shop.palaceskateboards.com', label: 'Palace EU' },
  { value: 'https://shop-jp.palaceskateboards.com', label: 'Palace JP' },
  { value: 'https://shop-usa.palaceskateboards.com', label: 'Palace US' },
  { value: 'https://par5-milano-yeezy.com', label: 'Par5 Milano Yeezy' },
  { value: 'https://shop.reigningchamp.com', label: 'Reigning Champ' },
  { value: 'https://www.renarts.com', label: 'Renarts' },
  { value: 'https://rise45.com', label: 'Rise45' },
  { value: 'https://www.rsvpgallery.com', label: 'RSVP Gallery' },
  { value: 'https://www.saintalfred.com', label: 'Saint Alfred' },
  { value: 'https://www.shoegallerymiami.com', label: 'Shoe Gallery Miami' },
  { value: 'https://www.shophny.com', label: 'Sneaker Lounge New York' },
  { value: 'https://shopnicekicks.com', label: 'Shop Nice Kicks' },
  { value: 'https://sneakerpolitics.com', label: 'Sneaker Politics' },
  { value: 'https://www.socialstatuspgh.com', label: 'Social Status' },
  { value: 'https://www.soleheaven.com', label: 'Sole Heaven' },
  { value: 'https://www.staplepigeon.com', label: 'Staple Pigeon' },
  { value: 'https://www.stoneisland.co.uk', label: 'Stone Island UK' },
  { value: 'https://www.stussy.com', label: 'Stussy' },
  { value: 'https://www.stussy.co.uk', label: 'Stussy UK' },
  { value: 'https://thepremierstore.com', label: 'Premier Store' },
  { value: 'https://shop.travisscott.com', label: 'Travis Scott Shop' },
  { value: 'https://www.trophyroomstore.com', label: 'Trophy Room Store' },
  { value: 'https://undefeated.com', label: 'Undefeated' },
  { value: 'https://unionjordan.com', label: 'Union Jordon' },
  { value: 'https://secure.unionjordan.com', label: 'Union Jordan Secure' },
  { value: 'https://store.unionlosangeles.com', label: 'Union Los Angeles' },
  { value: 'https://www.unknwn.com', label: 'Unknwn' },
  { value: 'https://wishatl.com', label: 'WishATL' },
  { value: 'https://www.xhibition.co', label: 'Xhibition' },
];

export const supremeSites = [
  { value: 'https://www.supremenewyork.com/', label: 'Supreme US' },
  { value: 'https://www.supremenewyork.com/eu', label: 'Supreme EU' },
  { value: 'https://www.supremenewyork.com/jp', label: 'Supreme JP' },
];

export const snipesSites = [
  { region: 'www.footlocker.com', label: 'Footlocker US', value: 'https://www.footlocker.com/' },
  { region: 'www.footlocker.ca', label: 'Footlocker CA', value: 'https://www.footlocker.ca/' },
  { region: 'www.kidsfootlocker.com', label: 'Kids Footlocker', value: 'https://www.kidsfootlocker.com/' },
  { region: 'www.eastbay.com', label: 'Eastbay', value: 'https://www.eastbay.com/' },
  { region: 'www.footaction.com', label: 'Footaction', value: 'https://www.footaction.com/' },
  { region: 'www.champssports.com', label: 'Champs Sports', value: 'https://www.champssports.com/' },
  { region: 'CZ', label: 'Footlocker CZ', value: 'https://www.footlocker.cz/' },
  { region: 'PL', label: 'Footlocker PL', value: 'https://www.footlocker.pl/' },
  { region: 'DK', label: 'Footlocker DK', value: 'https://www.footlocker.dk/' },
  { region: 'IE', label: 'Footlocker IE', value: 'https://www.footlocker.ie/' },
  { region: 'SE', label: 'Footlocker SE', value: 'https://www.footlocker.se/' },
  { region: 'PT', label: 'Footlocker PT', value: 'https://www.footlocker.pt/' },
  { region: 'HU', label: 'Footlocker HU', value: 'https://www.footlocker.dk/' },
  { region: 'GR', label: 'Footlocker GR', value: 'https://www.footlocker.gr/' },
  { region: 'AT', label: 'Footlocker AT', value: 'https://www.footlocker.at/' },
];

export const checkoutTypes = [
  { value: 'ftl-pp', label: 'Manual Paypal' },
  { value: 'ftl-cc', label: 'Credit Card' },
];

export const ysSites = [{ value: 'https://www.yeezysupply.com/', label: 'Yeezy Supply US' }];

export const monitorTypes = [
  { value: 'keywords', label: 'Keywords' },
  { value: 'url', label: 'URL' },
  { value: 'variant', label: 'Variants' },
];

export const ShopifyModes = [
  { value: 'advanced', label: 'Advanced' },
  { value: 'safe', label: 'Safe' },
];
export const SnipesModes = [
  { value: 'fast', label: 'Fast' },
  { value: 'api', label: 'Api Safe' },
];
export const supremeModes = [{ value: 'advanced', label: 'Advanced' }];
export const sizes = [
  { value: 'random', label: 'Random' },
  { value: '4', label: '4' },
  { value: '4.5', label: '4.5' },
  { value: '5', label: '5' },
  { value: '5.5', label: '5.5' },
  { value: '6', label: '6' },
  { value: '6.5', label: '6.5' },
  { value: '7', label: '7' },
  { value: '7.5', label: '7.5' },
  { value: '8', label: '8' },
  { value: '8.5', label: '8.5' },
  { value: '9', label: '9' },
  { value: '9.5', label: '9.5' },
  { value: '10', label: '10' },
  { value: '10.5', label: '10.5' },
  { value: '11', label: '11' },
  { value: '11.5', label: '11.5' },
  { value: '12', label: '12' },
  { value: '12.5', label: '12.5' },
  { value: '13', label: '13' },
  { value: '13.5', label: '13.5' },
  { value: '14', label: '14' },
  { value: '15', label: '15' },
  { value: '16', label: '16' },
  { value: 'xxs', label: 'XXS' },
  { value: 'xs', label: 'XS' },
  { value: 'small', label: 'S' },
  { value: 'medium', label: 'M' },
  { value: 'large', label: 'L' },
  { value: 'xlarge', label: 'XL' },
  { value: 'xxlarge', label: 'XXL' },
];
export const shopifySizes = [
  { value: 'random', label: 'Random' },
  { value: '4', label: '4' },
  { value: '4.5', label: '4.5' },
  { value: '5', label: '5' },
  { value: '5.5', label: '5.5' },
  { value: '6', label: '6' },
  { value: '6.5', label: '6.5' },
  { value: '7', label: '7' },
  { value: '7.5', label: '7.5' },
  { value: '8', label: '8' },
  { value: '8.5', label: '8.5' },
  { value: '9', label: '9' },
  { value: '9.5', label: '9.5' },
  { value: '10', label: '10' },
  { value: '10.5', label: '10.5' },
  { value: '11', label: '11' },
  { value: '11.5', label: '11.5' },
  { value: '12', label: '12' },
  { value: '12.5', label: '12.5' },
  { value: '13', label: '13' },
  { value: '13.5', label: '13.5' },
  { value: '14', label: '14' },
  { value: '15', label: '15' },
  { value: '16', label: '16' },
  { value: 'xxs', label: 'XXS' },
  { value: 'xs', label: 'XS' },
  { value: 's', label: 'S' },
  { value: 'm', label: 'M' },
  { value: 'l', label: 'L' },
  { value: 'xl', label: 'XL' },
  { value: 'xxl', label: 'XXL' },
];

export const snipesSizes = [
  { value: 'random', label: 'Random' },
  { value: '04.0', label: '4' },
  { value: '04.5', label: '4.5' },
  { value: '05.0', label: '5' },
  { value: '05.5', label: '5.5' },
  { value: '06.0', label: '6' },
  { value: '06.5', label: '6.5' },
  { value: '07.0', label: '7' },
  { value: '07.5', label: '7.5' },
  { value: '08.0', label: '8' },
  { value: '08.5', label: '8.5' },
  { value: '09.0', label: '9' },
  { value: '09.5', label: '9.5' },
  { value: '10.0', label: '10' },
  { value: '10.5', label: '10.5' },
  { value: '11.0', label: '11' },
  { value: '11.5', label: '11.5' },
  { value: '12.0', label: '12' },
  { value: '12.5', label: '12.5' },
  { value: '13.0', label: '13' },
  { value: '13.5', label: '13.5' },
  { value: '14.0', label: '14' },
  { value: '15.0', label: '15' },
  { value: '16.0', label: '16' },
  { value: '36', label: '36' },
  { value: '36 1/3', label: '36 1/3' },
  { value: '36 2/3', label: '36 2/3' },
  { value: '37', label: '37' },
  { value: '37 1/3', label: '37 1/3' },
  { value: '37 2/3', label: '37 2/3' },
  { value: '38', label: '38' },
  { value: '38 1/3', label: '38 1/3' },
  { value: '38 2/3', label: '38 2/3' },
  { value: '39', label: '39' },
  { value: '39 1/3', label: '39 1/3' },
  { value: '40', label: '40' },
  { value: '40 1/3', label: '40 1/3' },
  { value: '40 2/3', label: '40 2/3' },
  { value: '41', label: '41' },
  { value: '41 1/3', label: '41 1/3' },
  { value: '41 2/3', label: '41 2/3' },
  { value: '42', label: '42' },
  { value: '42 1/3', label: '42 1/3' },
  { value: '42 2/3', label: '42 2/3' },
  { value: '43', label: '43' },
  { value: '43 1/3', label: '43 1/3' },
  { value: '43 2/3', label: '43 2/3' },
  { value: '44', label: '44' },
  { value: '44 1/3', label: '44 1/3' },
  { value: '44 2/3', label: '44 2/3' },
  { value: '45', label: '45' },
  { value: '45 1/3"', label: '45 1/3"' },
  { value: '45 2/3', label: '45 2/3' },
  { value: '46', label: '46' },
  { value: '46 1/3', label: '46 1/3' },
  { value: '46 2/3', label: '46 2/3' },
  { value: '47', label: '47' },
  { value: '47 1/3', label: '47 1/3' },
  { value: '47 2/3', label: '47 2/3' },
  { value: '48', label: '48' },
  { value: '48 1/3', label: '48 1/3' },
  { value: '48 2/3', label: '48 2/3' },
  { value: '49', label: '49' },
  { value: '49 1/3', label: '49 1/3' },
  { value: '49 2/3', label: '49 2/3' },
  { value: '50', label: '50' },
  { value: 'xxs', label: 'XXS' },
  { value: 'xs', label: 'XS' },
  { value: 's', label: 'S' },
  { value: 'm', label: 'M' },
  { value: 'l', label: 'L' },
  { value: 'xl', label: 'XL' },
  { value: 'xxl', label: 'XXL' },
];

export const categories = [
  { value: 'new', label: 'New' },
  { value: 'Jackets', label: 'Jackets' },
  { value: 'Shirts', label: 'Shirts' },
  { value: 'Tops/Sweaters', label: 'Tops/Sweaters' },
  { value: 'T-Shirts', label: 'T-Shirts' },
  { value: 'Sweatshirts', label: 'Sweatshirts' },
  { value: 'Pants', label: 'Pants' },
  { value: 'Shorts', label: 'Shorts' },
  { value: 'Hats', label: 'Hats' },
  { value: 'Bags', label: 'Bags' },
  { value: 'Accessories', label: 'Accessories' },
  { value: 'Shoes', label: 'Shoes' },
  { value: 'Skate', label: 'Skate' },
];
