export default {
  preCarting: 'Preparing checkout',
  beginningCheckout: 'Beginning checkout',
  taskError: 'Task error, retrying',
  monitoring: 'Monitoring',
  foundProduct: 'Found product',
  selectedSize: 'Selected size',
  gettingSizeId: 'Getting size ID',
  productNotFound: 'Product not found',
  prepare: 'Preparing session',
  handleInputError: 'Handling input error',
  handlePaymentError: 'Handling payment error',
  password: 'Password page',
  restock: 'Waiting for restock',
  carting: 'Adding to cart',
  creatingCheckout: 'Creating checkout',
  gettingProperties: 'Getting properties',
  gettingCSRF: 'Getting CSRF token',
  oos: 'OOS, retrying',
  cartingError: 'Add to cart error',
  cartingFailedOOS: 'Product OOS, retrying ATC',
  cartError: 'Cart error',
  timeout: 'Timeout',
  proxyError: 'Proxy error',
  proxyBanned: 'Banned',
  pxBlocked: 'Blocked by PX',
  variantError: 'Variant error',
  checkpoint: 'Submitting checkpoint',
  proceedingCeckout: 'Proceeding to checkout',
  proceedingPayment: 'Proceeding to payment',
  proceedingPaymentError: 'Proceeding to payment error',
  submittingInformation: 'Submitting information',
  submittingInformationError: 'Submitting information error',
  submittingShipping: 'Submitting shipping',
  submittingShippingError: 'Submitting shipping error',
  invalidAddress: 'Invalid address',
  submittingBilling: 'Submitting billing',
  submittingBillingError: 'Submitting billing error',
  gettingCheckoutPage: 'Getting payment page',
  gettingCheckout: 'Getting checkout url',
  waitingRates: 'Getting shipping rate',
  gotRates: 'Got shipping rate',
  caculatingTaxes: 'Calculating taxes',
  waitingCaptcha: 'Waiting for captcha',
  waitingDelay: 'Waiting for delay',
  waitingProduct: 'Waiting for product',
  waitingRelease: 'Waiting for release',
  submitPaymentError: 'Submit payment error',
  submittingPayment: 'Submitting payment',
  mergingCheckout: 'Merging checkout',
  submittingOrder: 'Submitting order',
  supremeCheckoutForm: 'Getting form',
  supremeDuplicate: 'Duplicate order',
  supremeInvalidColor: 'Invalid color',
  initiateThreeDS: 'Intiating 3DS processing',
  cardCheck: 'Processing 3DS card data',
  queue: 'Queue',
  queueError: 'Queue error',
  processing: 'Processing',
  processingError: 'Processing error',
  declined: 'Declined',
  success: 'Success',
  successBank: 'Success! Check Discord to pay',
  successPaypal: 'Success! Check window',
  failed: 'Failed',
  failedToQueue: 'Failed to Queue',
};
